import { existsSync } from 'fs'
import { join } from 'path'
import { detectWorktree } from '../lib/worktree.ts'
import { loadConfig, configExists, getComposeFile } from '../lib/config.ts'
import { runCompose, getOverrideRelativePath } from '../lib/compose.ts'
import * as output from '../lib/output.ts'

/**
 * Run an arbitrary docker compose command with automatic -f flags
 *
 * This allows running any docker compose command while automatically
 * including the project's compose file and the port override file.
 *
 * @param args - Arguments to pass to docker compose
 */
export async function compose(args: string[]): Promise<void> {
  // Detect worktree info
  let worktreeInfo
  try {
    worktreeInfo = detectWorktree()
  } catch (error) {
    output.error(`${error}`)
    process.exit(1)
  }

  const { repoRoot, worktreePath, name } = worktreeInfo

  // Check if port is initialized
  if (!configExists(repoRoot)) {
    output.error('Port not initialized. Run "port init" first.')
    process.exit(1)
  }

  // Load config
  let config
  try {
    config = await loadConfig(repoRoot)
  } catch (error) {
    output.error(`Failed to load config: ${error}`)
    process.exit(1)
  }

  const composeFile = getComposeFile(config)
  const overridePath = getOverrideRelativePath()

  // Check if the compose file exists
  if (!existsSync(join(worktreePath, composeFile))) {
    output.error(`Compose file not found: ${composeFile}`)
    process.exit(1)
  }

  // Check if override file exists (generated by `port up`)
  const overrideFullPath = join(worktreePath, overridePath)
  if (!existsSync(overrideFullPath)) {
    output.error(`Override file not found. Run "port up" first to generate ${overridePath}`)
    process.exit(1)
  }

  // Run the compose command with automatic -p and -f flags
  const { exitCode } = await runCompose(worktreePath, composeFile, name, args)
  process.exit(exitCode)
}
