import { existsSync } from 'fs'
import { join } from 'path'
import { detectWorktree } from '../lib/worktree.ts'
import { loadConfig, configExists, getComposeFile, PORT_DIR } from '../lib/config.ts'
import { getComposeCommand, getOverrideRelativePath } from '../lib/compose.ts'
import { execWithStdio } from '../lib/exec.ts'
import * as output from '../lib/output.ts'

/**
 * Run an arbitrary docker compose command with automatic -f flags
 *
 * This allows running any docker compose command while automatically
 * including the project's compose file and the port override file.
 *
 * @param args - Arguments to pass to docker compose
 */
export async function compose(args: string[]): Promise<void> {
  // Detect worktree info
  let worktreeInfo
  try {
    worktreeInfo = detectWorktree()
  } catch (error) {
    output.error(`${error}`)
    process.exit(1)
  }

  const { repoRoot, worktreePath, name } = worktreeInfo

  // Check if port is initialized
  if (!configExists(repoRoot)) {
    output.error('Port not initialized. Run "port init" first.')
    process.exit(1)
  }

  // Load config
  let config
  try {
    config = await loadConfig(repoRoot)
  } catch (error) {
    output.error(`Failed to load config: ${error}`)
    process.exit(1)
  }

  const composeFile = getComposeFile(config)
  const overridePath = getOverrideRelativePath()

  // Check if the compose file exists
  if (!existsSync(join(worktreePath, composeFile))) {
    output.error(`Compose file not found: ${composeFile}`)
    process.exit(1)
  }

  // Check if override file exists (generated by `port up`)
  const overrideFullPath = join(worktreePath, overridePath)
  if (!existsSync(overrideFullPath)) {
    output.error(`Override file not found. Run "port up" first to generate ${overridePath}`)
    process.exit(1)
  }

  // Get the docker compose command
  const cmd = await getComposeCommand()

  // Build the full command with -f flags
  // Format: docker compose -p <project> -f <compose> -f <override> <user-args>
  const fullArgs = ['-p', name, '-f', composeFile, '-f', overridePath, ...args]

  const fullCommand = `${cmd} ${fullArgs.join(' ')}`

  // Execute with stdio inherited for interactive commands
  try {
    const { exitCode } = await execWithStdio(fullCommand, { cwd: worktreePath })
    process.exit(exitCode)
  } catch (error) {
    output.error(`Failed to execute docker compose: ${error}`)
    process.exit(1)
  }
}
