import { writeFile } from 'fs/promises'
import { resolve } from 'path'
import * as output from '../lib/output.ts'
import { detectWorktree } from '../lib/worktree.ts'
import { guideEntriesByCategory, PORT_SUMMARY } from '../lib/commandGuide.ts'

const RECOMMENDED_COMMANDS = guideEntriesByCategory('recommended')
const ADDITIONAL_COMMANDS = guideEntriesByCategory('additional')
const USEFUL_CHECKS = guideEntriesByCategory('useful')

/**
 * Generate markdown content from the shared command guide data structure.
 */
export function generateMarkdown(): string {
  const lines: string[] = []

  lines.push('<!-- Generated by: port onboard --md -->')
  lines.push('')
  lines.push('# Port Onboarding')
  lines.push('')
  lines.push(PORT_SUMMARY)
  lines.push('')
  lines.push('## Recommended Flow')
  lines.push('')

  for (const [index, step] of RECOMMENDED_COMMANDS.entries()) {
    lines.push(`### ${index + 1}. \`${step.command}\``)
    lines.push('')
    lines.push(`- **How**: ${step.how}`)
    lines.push(`- **Why**: ${step.why}`)
    lines.push('')
  }

  lines.push('## Additional Commands')
  lines.push('')
  for (const step of ADDITIONAL_COMMANDS) {
    lines.push(`- **\`${step.command}\`**: ${step.why}`)
    lines.push(`  - ${step.how}`)
  }
  lines.push('')

  lines.push('## Useful Checks')
  lines.push('')
  for (const step of USEFUL_CHECKS) {
    lines.push(`- \`${step.command}\`: ${step.description}`)
  }
  lines.push('')

  return lines.join('\n')
}

/**
 * Print a focused onboarding guide for common Port workflows.
 * When --md is passed, writes an ONBOARD.md file to the repo root.
 */
export async function onboard(options?: { md?: boolean }): Promise<void> {
  if (options?.md) {
    const { repoRoot } = detectWorktree()
    const markdown = generateMarkdown()
    const filePath = resolve(repoRoot, 'ONBOARD.md')
    await writeFile(filePath, markdown)
    output.success(`Wrote ${filePath}`)
    return
  }

  output.header('Port onboarding')
  output.newline()
  output.dim(PORT_SUMMARY)
  output.newline()
  output.info('Recommended flow:')
  output.newline()

  for (const [index, step] of RECOMMENDED_COMMANDS.entries()) {
    output.header(`${index + 1}. ${output.command(step.command)}`)
    output.dim(`   How: ${step.how}`)
    output.dim(`   Why: ${step.why}`)
    output.newline()
  }

  output.info('Additional commands:')
  for (const step of ADDITIONAL_COMMANDS) {
    output.header(`- ${output.command(step.command)}`)
    output.dim(`  ${step.why}`)
    output.dim(`  ${step.how}`)
  }
  output.newline()

  output.info('Useful checks:')
  for (const step of USEFUL_CHECKS) {
    output.dim(`- ${output.command(step.command)}: ${step.description}`)
  }
}
