import { writeFileSync } from 'fs'
import { dirname, resolve } from 'path'
import { fileURLToPath } from 'url'
import { COMMAND_GUIDE, type CommandGuideEntry, PORT_SUMMARY } from '../src/lib/commandGuide.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')
const skillPath = resolve(repoRoot, 'skills/port-cli/SKILL.md')

function flags(entry: CommandGuideEntry): string {
  const values: string[] = []
  if (entry.privileged) values.push('privileged')
  if (entry.destructive) values.push('destructive')
  return values.length > 0 ? ` (${values.join(', ')})` : ''
}

export function generatePortSkillMarkdown(): string {
  const lines: string[] = []

  lines.push('---')
  lines.push('name: port-cli')
  lines.push('description: >')
  lines.push('  Use when managing git worktrees and local services with the Port CLI,')
  lines.push('  including setup, entering worktrees, running Docker Compose or host')
  lines.push('  processes, viewing URLs/status, and cleaning up safely.')
  lines.push('---')
  lines.push('')
  lines.push('# Port CLI')
  lines.push('')
  lines.push('<!-- Generated by: scripts/generate-port-skill.ts -->')
  lines.push('')
  lines.push(PORT_SUMMARY)
  lines.push('')
  lines.push('## Safety Rules')
  lines.push('')
  lines.push('- Inspect state before changing it: prefer `port status`, `port list`, and')
  lines.push('  `port urls` first.')
  lines.push('- Ask before privileged machine setup with `port install` or `port uninstall`.')
  lines.push('- Ask before destructive cleanup: `port remove`, `port prune`, and')
  lines.push('  `port cleanup` can delete worktrees, branches, containers, volumes, or')
  lines.push('  images.')
  lines.push('- Do not read or print secret environment files while troubleshooting Port projects.')
  lines.push('- If shell integration is not installed, `port enter` and `port exit` may')
  lines.push('  print a `cd` command instead of changing the current shell directory.')
  lines.push('')
  lines.push('## First-Time Setup')
  lines.push('')
  lines.push('Use this workflow when a repository has not been prepared for Port yet:')
  lines.push('')
  lines.push('```bash')
  lines.push('port onboard')
  lines.push('port init')
  lines.push('port install')
  lines.push('```')
  lines.push('')
  lines.push("Then add shell integration to the user's shell profile:")
  lines.push('')
  lines.push('```bash')
  lines.push('eval "$(port shell-hook bash)" # bash')
  lines.push('# or')
  lines.push('eval "$(port shell-hook zsh)"  # zsh')
  lines.push('# or')
  lines.push('port shell-hook fish | source  # fish')
  lines.push('```')
  lines.push('')
  lines.push('## Command Reference')
  lines.push('')
  lines.push('These commands are generated from `src/lib/commandGuide.ts`, the same')
  lines.push('metadata used by onboarding docs and command coverage tests.')
  lines.push('')

  for (const entry of COMMAND_GUIDE) {
    lines.push(`### \`${entry.command}\`${flags(entry)}`)
    lines.push('')
    lines.push(entry.description)
    lines.push('')
    lines.push(`- **How**: ${entry.how}`)
    lines.push(`- **Why**: ${entry.why}`)
    lines.push(`- **Agent guidance**: ${entry.agentGuidance}`)
    if (entry.aliases?.length) {
      lines.push(`- **Aliases**: ${entry.aliases.map(alias => `\`port ${alias}\``).join(', ')}`)
    }
    lines.push('')
  }

  lines.push('## Troubleshooting Checklist')
  lines.push('')
  lines.push('1. Run `port status` to see known worktrees and services.')
  lines.push('2. Run `port urls` inside the worktree to confirm expected hostnames.')
  lines.push('3. Verify Docker and Docker Compose are available when using `port up`.')
  lines.push('4. If domains do not resolve, confirm `port install` has been run for the')
  lines.push('   configured domain.')
  lines.push('5. If a branch name matches a Port command, use `port enter <branch>` instead')
  lines.push('   of `port <branch>`.')
  lines.push('6. For host processes, confirm the command respects the `PORT` environment')
  lines.push('   variable.')
  lines.push('')
  lines.push('## Reference')
  lines.push('')
  lines.push('- Project README: <https://github.com/jdtzmn/port#readme>')
  lines.push('- Install the CLI: `npm install -g @jdtzmn/port` or')
  lines.push('  `bun add -g @jdtzmn/port`')

  return lines.join('\n')
}

if (import.meta.main) {
  writeFileSync(skillPath, generatePortSkillMarkdown())
}
