import { describe, expect, test } from 'vitest'
import { normalizeRemoteSshHostPatterns, renderManagedSshConfig } from './sshConfig.ts'

describe('managed SSH host patterns', () => {
  test('normalizes explicit hosts and wildcards deterministically', () => {
    expect(normalizeRemoteSshHostPatterns(['DevBox', '*.OD', 'devbox', 'build-?.od'])).toEqual([
      '*.od',
      'build-?.od',
      'devbox',
    ])
  })

  test.each([
    { patterns: [] },
    { patterns: ['*'] },
    { patterns: ['?'] },
    { patterns: ['!devbox'] },
    { patterns: ['host,other'] },
    { patterns: ['host name'] },
    { patterns: ['host#comment'] },
    { patterns: ['host/path'] },
    { patterns: ['host%h'] },
    { patterns: ['host\\name'] },
    { patterns: ['\n'] },
  ])('rejects unsafe or global activation patterns: $patterns', ({ patterns }) => {
    expect(() => normalizeRemoteSshHostPatterns(patterns)).toThrow('Invalid SSH host pattern')
  })

  test('bounds pattern count and encoded size', () => {
    expect(() =>
      normalizeRemoteSshHostPatterns(Array.from({ length: 65 }, (_, index) => `host-${index}`))
    ).toThrow('Invalid SSH host pattern')
    expect(() => normalizeRemoteSshHostPatterns(['a'.repeat(254)])).toThrow(
      'Invalid SSH host pattern'
    )
  })
})

describe('managed SSH fragment', () => {
  test('renders only Port-owned connection lifecycle settings', () => {
    expect(renderManagedSshConfig(['devbox', '*.od']))
      .toBe(`# Generated by Port. Run port install --remote-services to update.
Host *.od devbox
    ControlMaster auto
    ControlPath /tmp/port-ssh-%C/s
    ControlPersist 3
    PermitLocalCommand yes
    LocalCommand port __remote-register %C
`)
  })
})
