const MAX_PATTERNS = 64
const MAX_PATTERN_BYTES = 253
const MAX_PATTERNS_BYTES = 4096
const safePattern = /^[a-z0-9*?._-]+$/i
const literalHostnameCharacter = /[a-z0-9]/i

function invalid(): never {
  throw new Error('Invalid SSH host pattern')
}

export function normalizeRemoteSshHostPatterns(patterns: readonly string[]): string[] {
  if (!Array.isArray(patterns) || patterns.length === 0 || patterns.length > MAX_PATTERNS) invalid()
  const normalized = patterns.map(pattern => {
    if (
      typeof pattern !== 'string' ||
      Buffer.byteLength(pattern) > MAX_PATTERN_BYTES ||
      !safePattern.test(pattern) ||
      !literalHostnameCharacter.test(pattern) ||
      pattern === '*'
    )
      invalid()
    return pattern.toLowerCase()
  })
  const unique = [...new Set(normalized)].sort()
  if (Buffer.byteLength(unique.join(' ')) > MAX_PATTERNS_BYTES) invalid()
  return unique
}

export function renderManagedSshConfig(patterns: readonly string[]): string {
  const hosts = normalizeRemoteSshHostPatterns(patterns)
  return [
    '# Generated by Port. Run port install --remote-services to update.',
    `Host ${hosts.join(' ')}`,
    '    ControlMaster auto',
    '    ControlPath /tmp/port-ssh-%C/s',
    '    ControlPersist 3',
    '    PermitLocalCommand yes',
    '    LocalCommand port __remote-register %C',
    '',
  ].join('\n')
}
